spring.application.name=D288_Task1_Backend_Project

# MySQL Connection Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/full-stack-ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=ecommerceapp
spring.datasource.password=secret

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.data.rest.base-path=/api

