spring.application.name=D288_Task1_Backend_Project

# This is the Database Connection Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/full-stack-ecommerce?createDatabaseIfNotExist=true
spring.datasource.username=Admin
spring.datasource.password=Passw0rd!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.data.rest.base-path=/api

